[package]
name = "FuckBF-Installer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fuckbf-i"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
reqwest = { version = "0.11.4", features = ["blocking"] }
colored = "2.0.0"
serde_json = "1.0.91"